name: Bug Report
description: File a bug report to help us improve ClearURL
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: browser
    attributes:
      label: Browser and Version
      description: Which browser and version are you using?
      placeholder: e.g., Chrome 120.0.6099.109, Firefox 121.0
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      placeholder: e.g., Windows 11, macOS 14.2, Ubuntu 22.04
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      description: Which version of ClearURL are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should have happened
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened instead
    validations:
      required: true

  - type: textarea
    id: test-urls
    attributes:
      label: Test URLs
      description: Please provide URLs where the issue occurs (remove sensitive information)
      placeholder: |
        https://example.com?utm_source=test&utm_medium=email
        https://another-site.com?fbclid=test123
    validations:
      required: false

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: Please copy any error messages from the browser console
      placeholder: Paste console errors here
      render: text
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop screenshots here
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I have searched existing issues for similar problems
          required: true
        - label: I have provided all the requested information
          required: true
        - label: This is not a security vulnerability (use security@clearurl-extension.org for security issues)
          required: true