name: Feature Request
description: Suggest a new feature or enhancement for ClearURL
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see added
      placeholder: Describe the feature you want to see implemented
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What need does it address?
      placeholder: Explain the problem or limitation this feature would address
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working?
      placeholder: Describe how you think this feature should work
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific examples of how this feature would be used
      placeholder: |
        1. When I visit site X, I need to...
        2. As a privacy-conscious user, I want to...
        3. This would help when...
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New tracking parameter support
        - User interface improvement
        - Performance enhancement
        - Privacy feature
        - Developer/power user feature
        - Integration with other tools
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Essential feature
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternative approaches you've considered
    validations:
      required: false

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas
      description: Do you have any ideas about how this could be implemented?
      placeholder: Share any technical ideas or implementation thoughts
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, screenshots, or examples
      placeholder: Drag and drop images or provide links to examples
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information that might be helpful
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I have searched existing issues and feature requests
          required: true
        - label: This feature aligns with the project's privacy-focused mission
          required: true
        - label: I understand this is a volunteer-driven project and features take time to implement
          required: true